apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mathgraph-prod
nameSuffix: -prod

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: prod
    includeSelectors: false

patches:
  - path: prod-patch.yaml
    target:
      kind: Job
  - path: pvc-patch.yaml

images:
  - name: mathgraph
    newTag: 0.1.0
