apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mathgraph-dev
nameSuffix: -dev

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: dev
    includeSelectors: false

patches:
  - path: dev-patch.yaml
    target:
      kind: Job

images:
  - name: mathgraph
    newTag: dev
